services:
  - type: web
    name: hyperedit
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    disk:
      name: sessions
      mountPath: /tmp/hyperedit-ffmpeg
      sizeGB: 10
